### ISSUE TITLE
Generate Access Token by validating TOTP challenge and if the machine is active

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-accounts-backend#14]
Accounts POST /machine/ABC123/token
IN totp
OUT machinePort=23433 
OUT token=BBCCCHHH3333

TOKEN=
- scope: machine-ABC123 localFw-127.0.0.1:23433

When TOTP is used only localFw is enabled because it is mean't to be used by the client side

**Comment by jairsjunior** [comment]
@flaviostutz we will use an external oauth2 solution like hydra or develop this mechanism at this project?
