### ISSUE TITLE
Create POST /accounts for registering new Accounts

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-accounts-backend#2]
Use MongoDB + NodeJS

**Comment by tiagostutz** [comment]
@eniovalo naquele estilo do que foi feito no OnBoarding...

**Comment by eniovalo** [comment]
@tiagostutz os campos que vou receber são os mencionados no projeto de frontend?  #1 
- email;
- password;
- max machines.

**Comment by tiagostutz** [comment]
Isso mesmo... esses serão obrigatórios, mas você não precisa manipular o JSON recebido no body da requisição... pode empurrar direto pro Mongo pq se precisarmos colocar mais informações a gente altera o Frontend e já vai...

**Comment by eniovalo** [comment]
> 
> 
> Isso mesmo... esses serão obrigatórios, mas você não precisa manipular o JSON recebido no body da requisição... pode empurrar direto pro Mongo pq se precisarmos colocar mais informações a gente altera o Frontend e já vai...

Entendi, então vou salvar todo o JSON recebido no Mongo. =]
Obrigado.

**Comment by tiagostutz** [comment]
@eniovalo I'm changing Dockerfile to FROM standard alpine, as it wont work pointing to:
```
FROM atf.intranet.bb.com.br:5001/bb/lnx/lnx-node-alpine
```

**Comment by eniovalo** [comment]
@tiagostutz , sorry. I forgot to change it. hehe
Thanks =)
