### ISSUE TITLE
Create "POST /account/[existing account_email]/machine" for new machine registration

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-accounts-backend#3]
Return:
text/plain
"XPK8793" -> [3 ALPHA + 4 NUMERIC]

HTTP Header: 
"Location: http://anyserver.com/account/ti@abracadabra.com/machine/XPK8793"

**Comment by ggrcha** [comment]
@flaviostutz how can i get domain to place on header, like the example above "anyserver.com"

**Comment by tiagostutz** [comment]
@ggrcha you could pass an environment variable with the BASE_DOMAIN
