### ISSUE TITLE
Create "GET /machine/[machineId]"

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-accounts-backend#4]
Return:
{ "machineId": "XPTO1111", "active": true, "machinePort": 14657 }

**Comment by ggrcha** [comment]
where could I check if the machine is active or not?

**Comment by tiagostutz** [comment]
For the first release, we can leave this `active` information out. So the payload would be only:
```
{
    "machineId": "IUZ6905",
    "tunnelPort": 33610,
}
```
PS - I changed the `machinePort` by `tunnelPort`.

**Comment by ggrcha** [comment]
where tunnel port is defined? it isn't persisted on mongo collection

**Comment by tiagostutz** [comment]
I think it would be better for the endpoint to be `GET machine/[machineId]`
I know there will be a challenge to guarantee a unique universal code among all the accounts, but for the user it will be much better to keep just one code in mind or event typed.

I'm changing the issue.

**Comment by tiagostutz** [comment]
> where tunnel port is defined? it isn't persisted on mongo collection

You are right, it didn't have, but now the "server agent" is sending this info on the enrollment phase
